# appveyor.yml reference : http://www.appveyor.com/docs/appveyor-yml

version: "1.0.10.{build}"

# Source Config
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - master
clone_folder: c:\gopath\src\github.com\pecigonzalo\docker-machine-vmwareworkstation
clone_depth: 5

# Build host

os: Windows Server 2012 R2

environment:
  GOPATH: c:\gopath
  matrix:
  - GOARCH: 386
    GOVERSION: 1.5.3
  - GOARCH: amd64
    GOVERSION: 1.5.3

init:
  - git config --global core.autocrlf input

# Build

install:
  - set Path=c:\go\bin;%Path%
  - echo %Path%
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-%GOARCH%.msi
  - msiexec /i go%GOVERSION%.windows-%GOARCH%.msi /q
  - go version
  - go env
  - go get -d -v -t ./...
  - go get golang.org/x/tools/cmd/vet

build_script:
  - go test -v ./...
  - go vet ./...
  - git rev-parse HEAD
  - go build -i -o ./bin/docker-machine-driver-vmwareworkstation_windows-%GOARCH%.exe ./cmd/

test: off

# Deploy
artifacts:
  - path: /bin/docker-machine-driver-vmwareworkstation_*-*.exe

deploy:
  provider: GitHub
  description: ' '
  auth_token:
    secure: QqxdbpN5rJhuQw42Iq4W6tdP1Lu4aw6y88QnHYC3tSQ9rzNuEI/q+qH4HGJ5WDpj
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only